name: splitty
description: Splitty, rewritten in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.15.7
  json_annotation: 2.0.0
  path: 1.6.2
  path_provider: 0.4.1
  quiver: 2.0.1

dev_dependencies:
  build_runner: 1.0.0
  json_serializable: 2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/plurals.json
    - assets/strings.json
