name: splitty
description: Splitty, rewritten in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  path: 1.6.2
  path_provider: 0.4.1
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/strings.json